org: bagelhouse
app: gdrive-s3-sync
	
service: gdrive-s3-sync
 
custom:
  serverless-offline:
    httpPort: 3001
  
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
 
functions:
  app:
    handler: ./dist/src/index.handler
    events: 
      - http:
          method: GET
          path: /auth

# package:
#   exclude:
#     - node_modules/**

plugins:
  - serverless-offline
  - serverless-express 	
